### ISSUE TITLE
Add an "info" endpoint for uploads

### ISSUE THREAD

**Issue by jkeck** [ivplus/aggregator#14]
To see:
- [x] how many MARC records are in the file
- [ ] how many deletes....
- [x] what the MARC format is?
- [x] file checksums (free with ActiveStorage)

**Comment by mejackreed** [comment]
Going to go ahead and unassign my self. We have what I think is something in play with #64 but I'm not clear if that fulfills "how many deletes"

**Comment by cbeer** [comment]
👍 let's split deletes to a new ticket.
