### ISSUE TITLE
File link from organization record

### ISSUE THREAD

**Issue by bobpersing** [ivplus/aggregator#282]
On the Organization record, the most recent file uploaded displays as a hyperlink.  In the attached screenshot of Dartmouth's record, the link is to the file "POD_2020120913_5335163770005706_new.xml".

Dartmouth reports that when they click on this link, they get a "You are not authorized to access this page" response.
When I click on it, I get a "The page you were looking for doesn't exist" response.
(I have the admin role on the system, but the Dartmouth user does not.)

What is the desired behavior when a user clicks on this link?  If the intent is to display the file in the browser, should that require special permissions, or should any user be able to display any file?

![organization screen](https://user-images.githubusercontent.com/74777933/101793311-a541de80-3ad3-11eb-90c4-4605d9981499.png)

**Comment by cbeer** [comment]
I strongly suspect this is fixed by #279 .

**Comment by cbeer** [comment]
It looks like there's a separate/related issue for non-admins too.
