### ISSUE TITLE
Handle MHLD data serialized into separate records

### ISSUE THREAD

**Issue by anarchivist** [ivplus/aggregator#300]
Yale (and others?) serialize holdings data as separate [MHLD](https://www.loc.gov/marc/holdings/) records interleaved into the dumps with the bib records. From Youn Noh at Yale:

> Our bib files include interleaved bib and holdings records. Not all bibs have holdings records. 
876 fields for items are added to the holdings record, and the LDR/17-18 of the holdings record is changed to 5i if there are items. 
A dot and sequence number are appended to the holdings record identifier if the record with items exceeds the permitted max length, and the record is duplicated for subsequent items. I'll need to use the same record identifier. 

Here's an example of a linked bib and holdings record:

<details><summary>Bib record</summary>

```
=LDR  00562cam a22002291  4500
=001  2782062
=005  20110310141917.0
=008  011002s1938\\\\ne\\\\\\\\\\\\000\0\ger\d
=035  \\$a(OCoLC)ocn684223972
=035  \\$9DHU5871YL
=035  \\$a2782062
=040  \\$aYUS$cYUS
=049  \\$aYUSW
=079  \\$aocm06803759
=099  \\$aK8$aAr6$aSch33
=100  1\$aSchilfgaarde, Paul van.
=245  14$aDie zielkunde van Aristoteles ...
=260  \\$aLeiden,$c1938.
=300  \\$a[1 v.]
=502  \\$aAkademisch proefschrift--Amsterdam.
=928  \\$aACOC1219
=948  \\$aRECON
```
</details>

<details><summary>Holdings record</summary>

```
=LDR  00262nx  a22001215i 4500
=001  3065598.0
=004  2782062
=005  20020514093448.0
=008  0205142u\\\\0\\\1001uu\\\0000000
=014  1\$aDHU5871YL001
=014  0\$9003140766
=852  80$bsmly$hK8$iAr6 Sch33
=876  \\$a6995770$p$t0
```
</details>

**Comment by cbeer** [comment]
Are these MARC21 MHLD records that are adjacent to the bib records? We're already combining those into a single logical record. That's how Stanford's MHLD records are, at least 🤷‍♂️

**Comment by anarchivist** [comment]
Yes, but I believe there can be multiple subsequent MHLD records (e.g. `bibA --> mhldA1 --> mhldA2 --> bibB mhldB1 -->  mhldB2`). If the combining logic works for this case I think we should be set.

**Comment by cbeer** [comment]
That's exactly how Stanford's records are.. so, yes?

**Comment by anarchivist** [comment]
![](https://media.tenor.com/images/0c6cede2c66bcc187c89fa47aed5c990/tenor.gif)
