### ISSUE TITLE
Dartmouth: issues with new stream

### ISSUE THREAD

**Issue by anarchivist** [ivplus/aggregator#344]
Reported on [POD Slack](https://pod4lib.slack.com/archives/CNUSQ71SB/p1618841635010200) by Eric Bivona: 

> After the POD Tech conversation last week, I tried to remediate Dartmouth’s contribution by creating a new stream, and adding all of the April contributions to it, using the upload[url] API request, in order, from the initial full for the month, through all of the deltas to date (as of Friday), in order, and then making the new stream, “202104” the default.  My code then added deltas to the stream after that.  Unfortunately, it looks like the initial uploads to the new stream never quite happened.  Is there something I should have done differently to make this work?  Can anything be done in the POD aggregator to resolve this?

**Comment by cbeer** [comment]
i’m looking at https://pod.stanford.edu/organizations/dartmouth/streams/202104; it looks like there’s a bunch of files we’ve failed to download, but when i click on them i get a 404.  If the successful files are anything to go by, it looks like they might be missing a `/`. That said, I can’t tell if the client sent the wrong urls, or if they sent the right right thing and we somehow mangled it (but not the others?)

**Comment by EJBivona** [comment]
As I said in the Slack channel, the URLs had typos from my end.  Having a better indication of the error in the stream display would have helped me figure this out earlier.
