### ISSUE TITLE
Document data upload approaches for providers

### ISSUE THREAD

**Issue by cbeer** [ivplus/aggregator#66]
Probably part of #163 

It should include a list of formats we accept (MARC21, MARCXML, and a plain text file of 001 field values as deletes)

It should include information about how to deliver dumps + deltas

<table>
<tr>
  <th>What you have</th><th>What to do</th>
</tr>
<tr><td>Full dumps in a single file</td><td>...</td></tr>
<tr><td>Full dumps as a compressed file</td><td>...</td></tr>
<tr><td>Full dumps chunked into multiple file</td><td>...</td></tr>
<tr><td>... and with deltas a single file (or, really two files: the MARC and the deletes)</td><td>Upload them to the stream; if provided as a single upload, deletes will be applied first followed by changes (so... any marc records in the delta will be present in the full dump.. if you need to retract records from the delta, either do that in pre-processing or add an additional upload with just the deletes to apply)</td></tr>
<tr><td>... and with deltas as a compressed file</td><td>Upload them to the stream... (and... see note about how we're processing deletes.) </td></tr>
<tr><td>... and with deltas chunked into multiple files</td><td>... (and... see note about how we're processing deletes.) </td></tr>
</table>

**Comment by anarchivist** [comment]
This is great. Can we make sure Bob knows about this ticket too? I'll give it a little more thought about how we might want to flesh this out, but I don't think I have much to add at the moment.
