### ISSUE TITLE
Demonstrate file uploads using CURL

### ISSUE THREAD

**Issue by jkeck** [ivplus/aggregator#7]

**Comment by hectorcorrea** [comment]
I created this document with some ideas for the data structure to support the files based on Chris initial commit. I also added a few sample HTTP calls to "visualize" how this could work:

https://docs.google.com/document/d/1sD7fCNfmZkpdhUsxcD6V4PoyY-LlGy6TOp3UTmE_99c/edit

**Comment by cbeer** [comment]
We determined devise-jwt is likely not appropriate for our use case. It might make sense if you were building a front-end javascript application, but its only affordance for getting signed tokens back out is part of the sign in workflow.

We need to consider alternative approaches to minting and managing organization tokens.
