### ISSUE TITLE
Upload content from the box folder to pod.stanford.edu

### ISSUE THREAD

**Issue by cbeer** [ivplus/aggregator#78]
These orgs have contributed data to the box folder:

- [x] Brown
- [x] Stanford
- [x] Duke
- [x] Penn
- [x] Cornell

Download the data and re-upload to pod.stanford.edu as uncompressed MARCXML or MARC21 (as delivered to box)

**Comment by mejackreed** [comment]
For Stanford which had an existing stream with data already present, I created a new stream using the Rails console on the server, and set it to default.

**Comment by mejackreed** [comment]
Given a directory of data that you want to upload, you can do the following:

```
ls -d $PWD/* | xargs -I{} printf "\-F 'upload[files][]=@%s' " {} {} | xargs curl -H 'Authorization: Bearer secretsecrettoken' --url http://127.0.0.1:3000/organizations/stanford/uploads
```

**Comment by mejackreed** [comment]
This works a little bit better.. curl each file individually
```
ls -d $PWD/* | xargs -I{} curl -sD - -o /dev/null -F 'upload[files][]=@{}' -H 'Authorization: Bearer secretsecrettoken' --url http://127.0.0.1:3000/organizations/brown/uploads
```

**Comment by mejackreed** [comment]
All org data has been uploaded and processed, though there have been some individual processing errors. Closing this.
