### ISSUE TITLE
Inject POD metadata into the generated full dump MARC records

### ISSUE THREAD

**Issue by cbeer** [ivplus/aggregator#94]
There was a proposal to add a 900$b with an organization code (that we'll probably want to capture + make configurable as part of the organization's metadata?).

It probably makes sense to add another subfield in the 900 to indicate that it's POD data?

Finally, we should expect to add other POD-specific data as convenient for our debugging, analysis, etc.

**Comment by jkeck** [comment]
Is there a particular step that we're imagining this would happen in? (i.e. on import, on analysis, on export, somewhere else?)

**Comment by cbeer** [comment]
We're currently producing these records in `GenerateDeltaDumpJob` and `GenerateFullDumpJob`.

**Comment by jkeck** [comment]
Sure, but we've demonstrated the possibility of using range requests to get a single MARC record from a binary file.  That MARC record would not have come from the resulting Delta/FullDump jobs.  If we were to support that, we would want that MARC record get the injected POD data also I imagine?

Without any requirements around getting out single records, I suppose we can ignore that for now, but something we might want to consider if we decide to actually build in/advertise support for that type of thing in the future.

**Comment by cbeer** [comment]
Good point; I don't think we've exposed the single-record endpoint anywhere right now, but it makes sense to me to augment it too 🤷‍♂️ . I guess that implies some "augmented marc record" method in `MarcRecord` that can be used.. wherever?

**Comment by jkeck** [comment]
Yeah, I like that idea.
